# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python -m django --version
  displayName: 'Install dependencies'

- script: |
     python manage.py migrate
  displayName: 'Run Django Migrations'

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://sast.aat.deloitte.com/scancentral-ctrl/'
    scanCentralClientToken: 'N^Q1xkt>9i<yURq>3YTm'
    sscUrl: 'https://ssc.aat.deloitte.com/ssc'
    sscCiToken: 'ce167069-1666-4abb-9ee1-84b034988219'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '21830'
    buildTool: 'none'
    pythonVersion: '3'
    pythonRequirementsFile: 'C:\Users\nmanisekar\OneDrive - Deloitte (O365D)\Desktop\pygoat\requirements.txt'
