# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


# Install dependencies
- script: 'pip install -r requirements.txt'
  displayName: 'Install Python Dependencies'

# Optional Python script run
- task: PythonScript@0
  displayName: 'Run Sample Python Script'
  inputs:
    scriptSource: inline
    script: |
      print("Hello, World!")

# Install Snyk CLI
- script: 'npm install -g snyk'
  displayName: 'Install Snyk CLI'

# Authenticate with Snyk
- script: 'snyk auth $(snyk_token)'
  displayName: 'Authenticate Snyk CLI'

# Run Snyk OSS Scan
- script: |
    snyk test --org=$(snyk_org_id) --project-name="TEST" 
  displayName: 'Run Snyk OSS Scan'

# Send results to Snyk dashboard (monitor)
- script: |
    snyk monitor --org=$(snyk_org_id) --project-name="TEST"
  displayName: 'Snyk Monitor with Dynamic Project Name'
  condition: succeededOrFailed()  # Always attempt to send results
  
