# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: AAT-Pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  

- script: |
    echo "Client Token: $(ScanCentral_ClientToken)"
    echo "SSC CI Token: $(ScanCentral_SscCiToken)"
    displayName: 'Debug Token Values'

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://sast.aat.deloitte.com/scancentral-ctrl/'
    scanCentralClientToken: '$(ScanCentral_ClientToken)'
    sscUrl: 'https://ssc.aat.deloitte.com/ssc'
    sscCiToken: '$(ScanCentral_SscCiToken)'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '21830'
    buildTool: 'none'
    pythonVersion: '3'
    pythonRequirementsFile: 'C:\Users\nmanisekar\OneDrive - Deloitte (O365D)\Desktop\GT-Security Tester\Snyk\pygoattest\requirements.txt'