# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: AAT-Pool

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: echo "Starting connectivity test to Fortify URLs"
  displayName: 'Start Connectivity Check'

- script: |
    echo "Testing Fortify SSC URL..."
    curl -L -I https://ssc.aat.deloitte.com/ssc || echo "Unable to reach Fortify SSC URL"
  displayName: 'Test Fortify SSC Connectivity'

- script: |
    echo "Testing Fortify ScanCentral URL..."
    curl -L -I https://sast.aat.deloitte.com/scancentral-ctrl || echo "Unable to reach Fortify ScanCentral URL"
  displayName: 'Test Fortify ScanCentral Connectivity'

- script: |
    echo "ScanCentral Client Token: $(ScanCentral.ClientToken)"
    echo "ScanCentral SSC CI Token: $(ScanCentral.SscCiToken)"
  displayName: 'Check Tokens'

  
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://sast.aat.deloitte.com/scancentral-ctrl'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'https://ssc.aat.deloitte.com/ssc'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '21830'
    buildTool: 'none'
    pythonVersion: '3'
    pythonRequirementsFile: 'C:\Users\nmanisekar\OneDrive - Deloitte (O365D)\Desktop\GT-Security Tester\Snyk\pygoattest\requirements.txt'