# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: AAT-Pool

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: echo "Starting connectivity test to Fortify URLs"
  displayName: 'Start Connectivity Check'

# Test Fortify SSC connectivity with token
- script: |
    echo "Testing Fortify SSC URL..."
    response=$(curl -s -o response.txt -w "%{http_code}" -X GET https://ssc.aat.deloitte.com/ssc/api/v1/ -H "Authorization: Bearer $(ScanCentral.SscCiToken)")
    
    echo "Response Code: $response"
    if [ "$response" -eq 200 ]; then
        echo "Successfully authenticated with Fortify SSC"
    else
        echo "Failed to authenticate with Fortify SSC. Response Code: $response"
        cat response.txt
    fi
  displayName: 'Test Fortify SSC Connectivity with Token'

# Test Fortify ScanCentral connectivity with token
- script: |
    echo "Testing Fortify ScanCentral URL..."
    response=$(curl -s -o response.txt -w "%{http_code}" -X GET https://sast.aat.deloitte.com/scancentral-ctrl/api/v1/ -H "Authorization: Bearer $(ScanCentral.ClientToken)")
    
    echo "Response Code: $response"
    if [ "$response" -eq 200 ]; then
        echo "Successfully authenticated with Fortify ScanCentral"
    else
        echo "Failed to authenticate with Fortify ScanCentral. Response Code: $response"
        cat response.txt
    fi
  displayName: 'Test Fortify ScanCentral Connectivity with Token'
  
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://sast.aat.deloitte.com/scancentral-ctrl'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'https://ssc.aat.deloitte.com/ssc'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '21830'
    buildTool: 'none'
    pythonVersion: '3'
    pythonRequirementsFile: 'C:\Users\nmanisekar\OneDrive - Deloitte (O365D)\Desktop\GT-Security Tester\Snyk\pygoattest\requirements.txt'