# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Step 1: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r $(Build.SourcesDirectory)/requirements.txt
  displayName: Install dependencies

# Step 2: Snyk scan
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'ADO Snyk test'
    testType: 'app'
    targetFile: '$(Build.SourcesDirectory)/requirements.txt'
    monitorWhen: 'never'
    failOnIssues: false
    projectName: 'PyGoat Snyk'
    organization: 'deloitte-internal-default'
