# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- script: 'pip install -r requirements.txt'
  displayName: 'Command Line Script'


- task: PythonScript@0
  displayName: 'Run a Python script'
  inputs:
    scriptSource: inline
    script: |
     # Simple Python script
     print("Hello, World!")


- script: 'npm install snyk -g'
  displayName: 'Install Snyk CLI'

#Your build pipeline references an undefined variable named ‘snyk_token’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972


- script: 'snyk auth $(snyk_token)'
  displayName: 'Authenticate Snyk CLI'


- script: |
   snyk test 
  displayName: 'Run Snyk OSS Scan'

#Your build pipeline references an undefined variable named ‘snyk_org_id’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972


- script: 'snyk monitor --org=$(snyk_org_id) '
  displayName: 'Run Snyk monitor'
  condition: succeededOrFailed()